## Promise.prototype.then 方法
1. then 方法的返回结果是 Promise 对象.
2. 此 Promise 对象 的 状态 由 then的回调函数决定

```
1. 回调函数 throw 一个东西 则 状态为 reject. 值为 抛出的异常的值
2. 回调函数 返回 一个 新的promise 对象 则状态由 这个 新的 promise对象 决定
3. 回调函数 返回其他任何类型 或者不返回 则 状态为 resolve 值为返回的其他任何类型 或者 undefined
```
## Promise.prototype.catch 方法
1. 用来指定Promise 失败后的回调 (语法糖)
2. 返回的值同样是一个 Promise 对象
3. 返回的Promise 对象的 状态 还是和then 一样
```
 const p = new Promise(function(resolve, reject){
     reject('出错了');
 })
 p.catch(function(reason){
     console.warn(reason); // 输出出错了
    
 })
```
## catch 和 then 都可以链式调用

```
const p = new Promise(function(resolve, reject){
        reject('我失败了'); // 这里如果reject 则直接到catch那里
                           // 这里如果 resolve 了 则到 下面的then 里面
    });
    const a = p.then(function(reason){ //成功的回调
        return new Promise((resolve, reject) => {
            resolve('我又成功了') // 这里如果 reject 则 到catch 那里 进行处理
        })
    }).catch((error)=>{ // 失败的回调
        console.warn(`捕获了${error}`);
        return false;
    });
    console.log(a);
```

